### ISSUE TITLE
Filter param or page param still present in url 

### ISSUE THREAD

**Issue by vshatylo** [EmicoEcommerce/Magento2Tweakwise#119]
URL is not updated properly after visiting 1 page or removing the filter when ajax is anabled
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.6
* Tweakwise Version: 5.7.3
* Tweakwise Export Version: 5.4.0
* Magento Deploy Mode: production

Pre-Conditions
Ajax filtering should be enabled
URL Strategy: QUERY PARAMS 

Steps to reproduce for page param
--
1. visit the category page where the page is applied. e.g. https://example.com/example_category_path?page=3
2. click on Page 1 in the pagination toolbar

Actual result
URL address still has value: https://example.com/example_category_path?page=3

Expected result
https://example.com/example_category_path

Steps to reproduce for filter param
--
1. visit the category page where the filter is applied. e.g. https://example.com/example_category_path?filter_name=filter_value
2. Click on the "uncheck" mark on the active filter

Actual result
URL address still has value: https://example.com/example_category_path?filter_name=filter_value
Expected result
https://example.com/example_category_path

**Comment by magextensions** [comment]
We have same issue.

**Comment by ahuininga-orisha** [comment]
@vshatylo @magextensions 

I can fix the problem for the page parameters. But i'm having trouble with the filter parameters. The problem is that in view/frontend/web/js/navigation-form.js on rule 382 the new url is combined with the current url. This is done to preserve additional parameters send in the url (for example an tracking url &trackingurl=test). 

The problem is that i can't see the difference in javascript between an deactivated filter and external parameters like tracking url. I can fix it for the pagination because it always is the same parameter. This doesn't work for filters.

To fix this problem I need to remove functionality that preserves the additional parameters. And that is something I can't do without discussing this internally.

If anybody has an better solution for this than removing the functionality, i'm open for suggestions.

**Comment by ahuininga-orisha** [comment]
#83 seems to be causing this issue. We intend to revert that change to fix this problem.
