### ISSUE TITLE
Filtering gives no results

### ISSUE THREAD

**Issue by vasiok32k** [EmicoEcommerce/Magento2Tweakwise#98]
When users use a filter with an ampersand (&) the site gives no results
--
For example - you can filter in the layered navigation. If you choose "Klauwlijm & blokjes" you get no results (while there are 23 items in the category), seems like it is because of the ampersand (&) in the chosen attribute.
![image](https://github.com/EmicoEcommerce/Magento2Tweakwise/assets/10946737/7b296037-2b88-48e6-9e0e-dff7051a2fc2)
![image](https://github.com/EmicoEcommerce/Magento2Tweakwise/assets/10946737/7d51b431-7cfb-4acf-8500-95ae2c846905)

If we replace the ampersand (&) in the URL with %26, it does work.

![image](https://github.com/EmicoEcommerce/Magento2Tweakwise/assets/10946737/04b4a02b-1119-4fa3-9843-6803f27b2de5)

We faced with that after updating module Tweakwise from 5.3.3 to 5.6.5, after some time of investigation we figured out that in version 5.4.0 it still works but already in 5.4.1 it isn't. So we dive into the changes what was added in this version and understood that it stop working after apply changes from this PR that was part of changes in version 5.4.1
https://github.com/EmicoEcommerce/Magento2Tweakwise/pull/37/files

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.5-p4
* Tweakwise Version: 5.6.3
* Tweakwise Export Version: 5.4.0
* Magento Deploy Mode: production and development

Steps to reproduce
--
1. Make sure that you have installed Tweakwise version higher than 5.4.0

Actual result
--
1. Go to the Product Listing Page (PLP)
2. In the Tweakwise Layered Navigation choose the attribute that contain ampersand (&) in the title and contains some products
3. Look on the result (no products)

Expected result
--
1. Go to the Product Listing Page (PLP)
2. In the Tweakwise Layered Navigation choose the attribute that contain ampersand (&) in the title and contains some products
3. Products shown as when filtering the options without ampersand (&) in the title.

**Comment by nkikkertyouwe** [comment]
I could also reproduce this on 5.7.0

**Comment by ahuininga-orisha** [comment]
@vasiok32k I can't seem to reproduce this locally. Locally the & character gets replaced bij the html encoding %26.

The only reason for the difference i can think of is that the character encoding of the & character is different. Can you test what happens if you do the following?

- Go to Stores->Attributes->Product->Attributes->Select the corresponding attribute (in the example "soort")
- In the properties tab under swatches. Remove every occurence of the & charcter en replace it with one typed in from your keyboard (no copy paste)
- Save the changes
- Run indexer:reindex
- Run an new tweakwise:export
- Wait for an new import and publish of the tweakwise instance.

Check if the problems still exists.

**Comment by ahuininga-orisha** [comment]
@vasiok32k Does the problem still exists? And did you try my suggestion?

**Comment by ahuininga-orisha** [comment]
@vasiok32k @nkikkertyouwe I've found an issue what may explain this problem. If you have double slug values in the tweakwise_attribuut_slug table than that may cause this issue. The problem is causes by attribuut values that have the same value but just different spelling. For example Black and black. Or Black/Blue and Black Blue. 

To fix this you need to make sure that the attribuut doesn't contain the same value with different spelling.

**Comment by ahuininga-orisha** [comment]
Closed issue due to inactivity
